# Pipeline for building Azure model-driven app code and all its extensions

trigger:
  branches:
    include:
    - '*'

name: '$(Build.SourceBranchName).$(Build.BuildId)'

pool:
  vmImage: 'windows-2022'

variables:
- group: ADDRESSES
- name: solution
  value: '**/MonkeyShock.Azure.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: version
  value: '1.0.1.$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@1
  displayName: Install Nuget 

- task: NuGetCommand@2
  displayName: Restore nugets for solution
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build VS solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: Copy Database project build to staging folder
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/MonkeyShock.Azure/Code/MonkeyShock.Azure.Database/bin/Release/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Database'

- task: CopyFiles@2
  displayName: Copy Web App project build to staging folder
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/MonkeyShock.Azure/Code/MonkeyShock.Azure.WebApi/bin/Release/net6.0/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/WebApi'

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DataverseSolutionArtifact'
